Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace MovieApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int CategoryId { get; set; }
    }
}

Models/MovieCategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class MovieCategoryModel
    {
        public Movie Movie { get; set; }
        public IEnumerable<Movie> Movies { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models 
{
    public static class Repository
    {
        private static List<Movie> _movies = null;

        static Repository()
        {
            _movies = new List<Movie>
            {
                new Movie(){ Id=1,
                    Name="Esaretin Bedeli",
                    ShortDescription="Esaretin Bedeli Filmi",
                    Description="<p><b>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</b></p>",
                    ImageUrl="1.jpg" },
                new Movie(){ Id=2,
                    Name="Baba",
                    ShortDescription="Baba Filmi",
                    Description="<p><b>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</b></p>",
                    ImageUrl="2.jpg" },
                new Movie(){ Id=3,
                    Name="Kara Şövalye",
                    ShortDescription="Kara Şövalye Filmi",
                    Description="<p><b>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</b></p>",
                    ImageUrl="3.jpg" },
                new Movie(){ Id=4,
                    Name="Dövüş Kulübü",
                    ShortDescription="Dövüş Kulübü Filmi",
                    Description="<p><b>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</b></p>",
                    ImageUrl="4.jpg" },
                new Movie(){ Id=5,
                    Name="Forrest Gump",
                    ShortDescription="Forrest Gump Filmi",
                    Description="<p><b>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</b></p>",
                    ImageUrl="5.jpg" },


            };
        }

        public static List<Movie> Movies
        {
            get
            {
                return _movies;
            }
        }

        public static void AddMovie(Movie entity)
        {
            _movies.Add(entity);
        }

        public static Movie GetById(int id)
        {
            return _movies.FirstOrDefault(i => i.Id == id);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieApp.Data;
using MovieApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Controllers
{
    public class HomeController : Controller
    {
        //Home/Index/3
        public IActionResult Index(int? id)
        {
            //ProductRepository.Movies
            //CategoryRepository.Categories

            //MovieCategoryModel model = new MovieCategoryModel();
            //model.Categories = CategoryRepository.Categories;
            //model.Movies = MovieRepository.Movies;

            var movies = MovieRepository.Movies;

            if (id != null)
            {
                movies = movies.Where(i => i.CategoryId == id).ToList();
            }

            return View(movies);
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            //MovieCategoryModel model = new MovieCategoryModel();
            //model.Categories = CategoryRepository.Categories;
            //model.Movie = MovieRepository.GetById(id);

            return View(MovieRepository.GetById(id));
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Details()
        {
            return View();
        }

        public IActionResult List()
        {
            return View();
        }
    }
}

ViewComponents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.ViewComponents
{
    public class CategoryMenuViewComponent :  ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            //{controller}/{action}/{id?}
            // /home/index/3
            // RouteData.Values[]
            if (RouteData.Values["action"].ToString() == "Index")
            {
                ViewBag.selectedCategory = RouteData?.Values["id"];
            }
            return View(CategoryRepository.Categories);
        }
    }
}

Views/Home/Contact.cshtml
<h1>
    Home/Contact
</h1>

Views/Home/Details.cshtml
@model Movie

<div class="row">
    <div class="col-md-3">
        @* @Html.Partial("_menu",Model.Categories) *@
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
            <div class="card mb-3">

                <div class="card-body">
                    <div class="row p-2">
                        <div class="col-md-4">
                            <img src="~/img/@Model.ImageUrl" alt="@Model.Description" class="card-img" />
                        </div>
                        <div class="col-md-8">
                            <h5 class="card-title">
                                <a asp-action="Details" asp-controller="Home" asp-route-id="@Model.Id"> @Model.Name</a> @*//home/details/3*@
                            </h5>
                            <p class="card-text">
                                @Html.Raw(Model.Description)
                            </p>
                            <p class="card-text">
                                <small class="text-muted">3 days ago</small>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>

Views/Home/Index.cshtml
@model IEnumerable<Movie>

<div class="row">
    <div class="col-md-3">
        @*@Html.Partial("_menu",Model.Categories)*@
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        @*
        @Html.Partial("_movies",Model)
        *@
        <!--Movie listesinden dönen filmler Model olarak _movies partial'ına gönderildi-->
        <partial name="_movies" model="Model"></partial>
    </div>
</div>

Views/Home/_movies.cshtml
@model IEnumerable<Movie>


@foreach (var movie in Model)
{
    <div class="card mb-3 border border-dark">
        <div class="row no-gutters border">
            <div class="col-md-3">
                <img src="~/img/@movie.ImageUrl" alt="@movie.Description" class="card-img" />
            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title">
                        <a asp-action="Details" asp-controller="Home" asp-route-id="@movie.Id"> @movie.Name</a> @*//home/details/3*@
                    </h5>
                    <p class="card-text">
                        @movie.ShortDescription
                    </p>
                    <p class="card-text">
                        <small class="text-muted">3 days ago</small>
                    </p>
                </div>
            </div>
        </div>
    </div>
}

Views/Movie/Details.cshtml
<h1>
    Movie/Details
</h1>

Views/Movie/Index.cshtml
<h1>
    Movie/Index
</h1>

Views/Movie/List.cshtml
<h1>
    Movie/List
</h1>

Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<div class="list-group">

    <a href="/" class="list-group-item list-group-item-action bg-dark text-white">
        Tüm Kategoriler
    </a>
    @foreach (var i in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-id="@i.Id"
           class="list-group-item list-group-item-action @(ViewBag.SelectedCategory == i.Id.ToString()?"active":"")">
            @i.Name
        </a>
    }

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <title>MovieApp</title>
</head>
<body>

    <header>
        @Html.Partial("_navbar")
    </header>
    <main>
        <div class="container mt-5">
            @RenderBody()
        </div>
    </main>
    <footer>
        @Html.Partial("_footer")
    </footer>
</body>
</html>

Views/Shared/_footer.cshtml
<div class="footer py-3 mt-3">
    <div class="container">
        <span class="text-muted">
            MovieApp 2020
        </span>
    </div>
</div>

Views/Shared/_menu.cshtml
@model IEnumerable<Category> 

<div class="list-group">

    @foreach (var i in Model)
    {
        <a href="#" class="list-group-item list-group-item-action">@i.Name</a>
    }

</div>

Views/Shared/_navbar.cshtml
<div class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a href="#" class="navbar-brand">MovieApp</a>

        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="/login" class="nav-link">Login</a>
            </li>
            <li class="nav-item">
                <a href="/register" class="nav-link">Register</a>
            </li>
        </ul>
    </div>
</div>